---
title: "2020 Fantasy Football"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
params: 
  per_id: 1
  leagueID: 847888
---

```{r setup, include=FALSE, cache=F}
library(flexdashboard)
library(tidyverse)
library(gt)
library(ggrepel)
knitr::opts_chunk$set(cache = F)
```

```{r,cache=F}
per_id <- params$per_id
leagueID <- params$leagueID
source("api_functions.R")
# set_per_id(1)
# set_league(847888)
```

Overview
===============================

Row {data-height=50}
-------------------------------------

### 

```{r}
valueBox(value = str_c(unlist(mug$team), collapse = " & "), caption = str_c("Week ", params$per_id, " Mug (Best Team): ", mug$week_points[1], " Points"), icon = "fa-pencil")
```

### 

```{r}
valueBox(value = str_c(unlist(plunger$team), collapse = " & "), caption = str_c("Week ", params$per_id, " Plunger (Worst Team): ", plunger$week_points[1], " Points"), icon = "fa-pencil")
```

### 

```{r}
valueBox(value = "Plunger / Mug Tally", caption = "Future Home Of",icon = "fa-pencil")

```

Row {data-height=350}
-------------------------------------
   
### 

```{r}
total_standings %>% select(-luck) %>% 
  mutate(week_win_perc = round(week_win_perc,2)) %>% 
  janitor::clean_names(case = "upper_camel") %>% 
  arrange(-WinPerc,-WeekWinPerc) %>% 
  gt() %>% 
  tab_header(title = "Weekly Standings") 

```   
    
### 

```{r}
plot_luck_chart(total_standings = total_standings)
```

Team Performance
===============================


Row {data-height=70}
-------------------------------------

### Biggest Team Underperformance: `r str_c(biggest_letdown$team, "\n", biggest_letdown$actual, " out of ", biggest_letdown$projected, " projected points")`

```{r}
gauge(biggest_letdown$actual %>% round(2), min = 0, max = biggest_letdown$projected %>% round(2), 
      gaugeSectors(danger = c(0, biggest_letdown$projected))
)

```

### Biggest Team Overperformance: `r str_c(outperformance$team, "\n", outperformance$actual, " out of ", outperformance$projected, " projected points")`

```{r}
gauge(outperformance$projected %>% round(2), min = 0, max = outperformance$actual %>% round(2), 
      gaugeSectors(success = c(0, outperformance$actual))
)
```

### Worst Coach Award:  `r str_c(coach_let_down$team, "\n", coach_let_down$week_points, " out of ", coach_let_down$best_points, " possible points")`

```{r}
gauge(coach_let_down$week_points, min = 0, max = coach_let_down$best_points, 
      gaugeSectors(danger = c(0, coach_let_down$best_points))
)

```

### Best Coach Award:  `r str_c(best_coach$team, "\n", best_coach$week_points, " out of ", best_coach$best_points, " possible points")`

```{r}
gauge(best_coach$week_points, min = 0, max = best_coach$best_points, 
      gaugeSectors(success = c(0, best_coach$best_points))
)

```


Row {data-height=350}
-------------------------------------
    
### Player Performance
    
```{r}
players_letting_down
```
    
### Coaching Performance

```{r}
letting_players_down
```

Team Report
===============================

Row {.tabset .tabset-fade}
-------------------------------------

``` {r, echo=FALSE, eval=TRUE}
# Create a number of tabs and associated plots based on the number of teams in the league.
out <- lapply(seq_along(plots), function(i){
  
  
  a1 <- knitr::knit_expand(text = sprintf("### %s\n", plots[[i]]$team)) # tab header, auto extracts names of `plot`
  a2 <- knitr::knit_expand(text = "\n```{r, fig.height=10,fig.width=10}") # start r chunk
  a3 <- knitr::knit_expand(text = sprintf("\nplots[[%d]]$plot", i)) # extract graphs by "writing" out `plots[[1]]$plot`, `plots[[1]]$plot` etc. to be rendered later
  a4 <- knitr::knit_expand(text = "\n```\n") # end r chunk

  paste(a1, a2, a3, a4, collapse = '\n') # collapse together all lines with newline separator

})

```
   
`r paste(knitr::knit(text = paste(out, collapse = '\n')))`
   

<!-- ### `r plots[[1]]$team` -->

<!-- ```{r,fig.height=10,fig.width=10} -->
<!-- plots[[1]]$plot -->
<!-- ```    -->

<!-- ### `r plots[[2]]$team` -->

<!-- ```{r,fig.height=10,fig.width=10} -->
<!-- plots[[2]]$plot -->
<!-- ``` -->


<!-- ### `r plots[[3]]$team` -->

<!-- ```{r,fig.height=10,fig.width=10} -->
<!-- plots[[3]]$plot -->
<!-- ``` -->


<!-- ### `r plots[[4]]$team` -->

<!-- ```{r,fig.height=10,fig.width=10} -->
<!-- plots[[4]]$plot -->
<!-- ``` -->


<!-- ### `r plots[[5]]$team` -->

<!-- ```{r,fig.height=10,fig.width=10} -->
<!-- plots[[5]]$plot -->
<!-- ``` -->


<!-- ### `r plots[[6]]$team` -->

<!-- ```{r,fig.height=10,fig.width=10} -->
<!-- plots[[6]]$plot -->
<!-- ``` -->


<!-- ### `r plots[[7]]$team` -->

<!-- ```{r,fig.height=10,fig.width=10} -->
<!-- plots[[7]]$plot -->
<!-- ``` -->


<!-- ### `r plots[[8]]$team` -->

<!-- ```{r,fig.height=10,fig.width=10} -->
<!-- plots[[8]]$plot -->
<!-- ``` -->

<!-- ### `r ifelse(number_of_teams>=9,plots[[9]]$team,"")` -->

<!-- ```{r,fig.height=10,fig.width=10} -->
<!-- plots[[8]]$plot -->
<!-- ``` -->


ESPN Predictions
===============================

```{r}
player_predictions_hist
```

